const var migration_list_urls_JSON = {
    "Achromic" : "achromic.hxi",
    "Aetheric" : "aetheric.hxi",
    "Atlas" : "atlas.hxi",
    "Blackout" : "blackout.hxi",
    "Blackout2" : "blackout2.hxi",
    "Bloom" : "bloom.hxi",
    "Cloudburst" : "cloudburst.hxi",
    "CloudburstAcoustic" : "cloudburstacoustic.hxi",
    "Endure" : "endure.hxi",
    "Found Keys" : "foundkeys.hxi",
    "Gloom" : "gloom.hxi",
    "MachineTribes" : "machinetribes.hxi",
    "Oracle" : "oracle.hxi",
    "Oracle2" : "oracle2.hxi",
    "PDQBass" : "pdqbass.hxi",
    "Portal" : "portal.hxi",
    "Prismatic" : "prismatic.hxi"}